### ISSUE TITLE
file deletion vulnerability

### ISSUE THREAD

**Issue by baDB0y111** [shadoweb/wdja#9]
Vulnerability file path：common/incfiles/manage_config.inc.php
![123](https://user-images.githubusercontent.com/34728397/71481796-40499600-283a-11ea-9407-b07673b25b37.png)
parameter file accept without filtered,attacker can delete any files with changed the file's value。
payload：admin/cache/manage.php?action=delete&file=../test.txt
![image](https://user-images.githubusercontent.com/34728397/71481973-23619280-283b-11ea-923b-1c715d82481b.png)

**Comment by shadoweb** [comment]
感谢反馈,因manage.php中已进行登录判断
wdja_cms_islogin();
未登录的用户使用admin/cache/manage.php?action=delete&file=../test.txt进行操作是没有权限的,会自动跳转到登录界面.
另外,因本系统后台集成文件管理功能,如登录后台,可以对当前网站的任意文件进行操作.

**Comment by baDB0y111** [comment]
这个漏洞的发生位置并不在文件管理的模块文件admin/files/manage.php中，而是缓存清除功能模块admin/cache/manage.php中，当在后台新建一个用户，并仅赋予其缓存清除权限，而不赋予其文件管理权限时，可通过此漏洞点删除网站任意文件。

**Comment by shadoweb** [comment]
感谢反馈,抽空修复一下,这个用户管理有点弱.

**Comment by shadoweb** [comment]
此问题已修复。下个版本中会进行更新。
